services:
  gateway:
    image: gateway
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    restart: always
  restarea:
    image: restarea
    env_file:
      - ./.env
    ports:
      - "8888:8888"
    restart: always
    environment:
      - SERVER_PORT=8888
      
  eureka:
    image: jiminu/eureka-serv:0.1.2-amd
    container_name: eureka
    ports:
      - "8765:8765"
    restart: always
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:8765/eureka